services:
  dev:
    container_name: seekster_api_dev
    image: seekster_api_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3005:3005
